Implements ReadFiles for reading multiple files from the specified fo…
onmetal/controller-utils pull request #16
Opened 2021-11-01 16:49 UTC by dmvolod

Adds ReadFiles function to be able read files from the specified folder including subfolders and having match function for filtering by file type/extension/whatever

fixes #9

2021-11-01 16:50 UTC, dmvolod commented
//cc @afritzler

2021-11-02 10:19 UTC, afritzler requested changes
Looks good to me! However, how about using https://pkg.go.dev/path/filepath#Glob instead of `WalkDir` for determining the objects location. So something like this:

```
files, err := filepath.Glob(srcDir + "/[a-Z0-9]")
```

2021-11-02 10:19 UTC, afritzler commented on unstructuredutils/unstructuredutils.go
> +func ReadFiles(root string, matchFun FileMatchFunc) ([]unstructured.Unstructured, error) {
```suggestion
func ReadFiles(root string, matchFunc FileMatchFunc) ([]unstructured.Unstructured, error) {
```

2021-11-02 11:43 UTC, dmvolod commented
> Looks good to me! However, how about using https://pkg.go.dev/path/filepath#Glob instead of `WalkDir` for determining the objects location. So something like this:

Good idea, @afritzler 
Implemented with the `filepath.Glob` and without separate filter function

2021-11-02 11:46 UTC, afritzler approved these changes

2021-11-04 08:14 UTC, merged